// automatically generated by the FlatBuffers compiler, do not modify

namespace FlatDasherSave
{

using System;
using FlatBuffers;

public sealed class FlatLevelSave : Table {
  public static FlatLevelSave GetRootAsLevelSave(ByteBuffer _bb) { return GetRootAsLevelSave(_bb, new FlatLevelSave()); }
  public static FlatLevelSave GetRootAsLevelSave(ByteBuffer _bb, FlatLevelSave obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public FlatLevelSave __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string LevelId { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetLevelIdBytes() { return __vector_as_arraysegment(4); }
  public float BestTime { get { int o = __offset(6); return o != 0 ? bb.GetFloat(o + bb_pos) : (float)0.0f; } }

  public static Offset<FlatLevelSave> CreateLevelSave(FlatBufferBuilder builder,
      StringOffset LevelIdOffset = default(StringOffset),
      float BestTime = 0.0f) {
    builder.StartObject(2);
    FlatLevelSave.AddBestTime(builder, BestTime);
    FlatLevelSave.AddLevelId(builder, LevelIdOffset);
    return FlatLevelSave.EndLevelSave(builder);
  }

  public static void StartLevelSave(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddLevelId(FlatBufferBuilder builder, StringOffset LevelIdOffset) { builder.AddOffset(0, LevelIdOffset.Value, 0); }
  public static void AddBestTime(FlatBufferBuilder builder, float BestTime) { builder.AddFloat(1, BestTime, 0.0f); }
  public static Offset<FlatLevelSave> EndLevelSave(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FlatLevelSave>(o);
  }
};

public sealed class FlatGameSave : Table {
  public static FlatGameSave GetRootAsGameSave(ByteBuffer _bb) { return GetRootAsGameSave(_bb, new FlatGameSave()); }
  public static FlatGameSave GetRootAsGameSave(ByteBuffer _bb, FlatGameSave obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public FlatGameSave __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public string Version { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetVersionBytes() { return __vector_as_arraysegment(4); }
  public FlatLevelSave GetLevelResults(int j) { return GetLevelResults(new FlatLevelSave(), j); }
  public FlatLevelSave GetLevelResults(FlatLevelSave obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int LevelResultsLength { get { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; } }

  public static Offset<FlatGameSave> CreateGameSave(FlatBufferBuilder builder,
      StringOffset VersionOffset = default(StringOffset),
      VectorOffset levelResultsOffset = default(VectorOffset)) {
    builder.StartObject(2);
    FlatGameSave.AddLevelResults(builder, levelResultsOffset);
    FlatGameSave.AddVersion(builder, VersionOffset);
    return FlatGameSave.EndGameSave(builder);
  }

  public static void StartGameSave(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddVersion(FlatBufferBuilder builder, StringOffset VersionOffset) { builder.AddOffset(0, VersionOffset.Value, 0); }
  public static void AddLevelResults(FlatBufferBuilder builder, VectorOffset levelResultsOffset) { builder.AddOffset(1, levelResultsOffset.Value, 0); }
  public static VectorOffset CreateLevelResultsVector(FlatBufferBuilder builder, Offset<FlatLevelSave>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartLevelResultsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatGameSave> EndGameSave(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FlatGameSave>(o);
  }
  public static void FinishGameSaveBuffer(FlatBufferBuilder builder, Offset<FlatGameSave> offset) { builder.Finish(offset.Value); }
};


}
